### Spring ###
spring:
  port: ${port:9951}
  application:
    name: math-api

### Feign ###
feign:
  client:
    config:
### Correio ###
      correio:
        connectTimeout: 300
        readTimeout: 1000
        loggerLevel: basic

correio:
  url: http://viacep.com.br