version: "2"

services:
  math-api-mongodb:
    image: "mongo:3.7-jessie"
    ports :
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=math-api_adm
      - MONGO_INITDB_ROOT_PASSWORD=math-api_adm
    command: --auth