version: "2"

services:
  rabbitmq-it:
    image: "rabbitmq:3.7-management-alpine"
    environment:
      RABBITMQ_DEFAULT_USER: "math-api_adm"
      RABBITMQ_DEFAULT_PASS: "math-api_adm"
      RABBITMQ_DEFAULT_VHOST: "/math-api"
    ports:
      - "5674:5672"
      - "15674:15672"