### Spring ###
spring:
  application:
    name: math-api

### Hystrix ###
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000

### Feign ###
feign:
  hystrix:
    enabled: true
  client:
    config:
### Feature Gateway ###
      feature-toggle:
        connectTimeout: 2000
        readTimeout: 3000
        loggerLevel: full

### Ribbon ###
ribbon:
  eureka:
    enabled: false

feature-toggle:
  ribbon:
    listOfServers: http://localhost:9801
    ConnectTimeout: 2000
    readTimeout: 3000
    maxTotalHttpConnections: 2
    maxConnectionsPerHost: 2